project_id = "drthfkbvxqjhuurmxjrk"

[functions.auth-register]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.send-email]
verify_jwt = true

[functions.password-reset]
verify_jwt = false